### ISSUE TITLE
error while clicking on premium button

### ISSUE THREAD

**Issue by SoundDr0ut** [Sobhan-SRZA/All-For-One-Bot#13]
![image](https://github.com/Sobhan-SRZA/All-For-One-Bot/assets/59321692/724291e9-11f4-477b-ac5c-52d663b3881b)

**Comment by Sobhan-SRZA** [comment]
Hi buddy,  don’t worry this is api error not source code error, after restart the source code or try again a while this will be fixed.
Thanks for using my source code❤️
